---
kind: pipeline
type: docker
name: api
steps:
- name: publish api
  image: plugins/docker
  settings:
    repo:
      from_secret: docker_repository
    context: api
    tags:
      - api-${DRONE_BRANCH}
    dockerfile: api/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    branch: [ master, develop ]

---
kind: pipeline
type: docker
name: web
steps:
- name: publish web
  image: plugins/docker
  settings:
    repo:
      from_secret: docker_repository
    context: web
    tags:
      - web-${DRONE_BRANCH}
    dockerfile: web/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    branch: [ master, develop ]
