version: '3.7'
services:
  api:
    image: kubebana:api-master
    build:
      context: api
    ports:
      - 5000:5000
    volumes:
      - ${HOME}/.kube/config:/root/.kube/config
    environment:
      - TZ=Europe/Berlin

  web:
    image: kubeana:web-master
    build:
      context: web
    depends_on:
      - server
    ports:
      - 80:80
    environment:
      - TZ=Europe/Berlin
      - VUE_APP_KUBEBANA_API_HOST=http://server:5000/
